### ISSUE TITLE
latest version of wartremover has Java 11 requirement.

### ISSUE THREAD

**Issue by SimY4** [augi/gradle-wartremover#12]
Latest release has Java 11 compat requirement. It'll be nice if we can keep it lower, at least on Java 8 level.

```
> java.lang.UnsupportedClassVersionError: cz/augi/gradle/wartremover/WartremoverPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Samle failing build:

https://travis-ci.org/SimY4/xpath-to-xml/jobs/604080189?utm_medium=notification&utm_source=github_status

**Comment by augi** [comment]
Thank you for reporting this issue! The problem was that TravisCI updated the `groovy` environment to be JDK 11 based. So I've setup the build to generate Java8 classes.

The fixed version will be released shortly.
