### ISSUE TITLE
Wartremove exclusions not working for repo on d:\ drive [v0.10.0, Windows 10]

### ISSUE THREAD

**Issue by Habitats** [augi/gradle-wartremover#18]
It seems the exclusion is not working when I have my repo on my d:\ drive as opposed to c:\. Not sure why that would matter, but it does.

This is what I have in my `build.gradle` and it's usually working flawlessly. However, I need to exclude all of the `errorWarts` in order for my project to compile if my repo lies on the d:\ drive.

```groovy
  wartremover {
    warningWarts = [
    ]
    errorWarts = [
        "OptionPartial",
        "FinalVal",
        "Return",
        "TryPartial",
        ...
    ]
    
    def testFiles = fileTree(project.projectDir.absolutePath + "/src/test/scala").collect { it.absolutePath }
    excludedFiles.addAll(testFiles + gRPCFiles + scalaxbFiles)
  }
```

**Comment by augi** [comment]
Hello, thank you for reporting this issue! Unfortunately, [this code](https://github.com/augi/gradle-wartremover/blob/master/src/main/groovy/cz/augi/gradle/wartremover/WartremoverPlugin.groovy#L80) shows that this Gradle plugin just passes the absolute filename to the wartremover core.

Could you please report your issue [in the wartremover project](https://github.com/wartremover/wartremover) instead? Thanks! 👍
