### ISSUE TITLE
Plugin is applied to all compile tasks

### ISSUE THREAD

**Issue by Z1kkurat** [augi/gradle-wartremover#2]
As title says, wartremover plugin is applied to all compile tasks including tests, example can be seen:   https://github.com/Z1kkurat/intellij-scala-wartremover/tree/gradle-plugin.  
In the example `gradlew clean build` causes test sources compilation to fail, thought I suppose it's not an expected behaviour.

**Comment by augi** [comment]
I believe that all the code should be treated in the same way, so all the code should be as clean as possible.

But your point is valid - maybe it's not expected. So I've updated the README.

**Comment by Z1kkurat** [comment]
Can you consider some optional configuration flag for disabling applying plugin to test sources? Sadly I can't get rid of unacceptable hacks in tests, so the plugin is currently not an option fot me...

**Comment by augi** [comment]
I've just released `0.9.2` that allows to have different configuration for tests. Hope it helps...
