### ISSUE TITLE
Default warts

### ISSUE THREAD

**Issue by Z1kkurat** [augi/gradle-wartremover#3]
Is it good to make some set of warts as warnings by default? It's more of a discussion that issue, because for example sbt plugin does not make any warts as warnings or errors by default AFAIK.

**Comment by augi** [comment]
I believe it's good. If you apply the plugin on your project then you IMHO want to check the code so sensible default makes sense for me.

Or in different words, it doesn't make any sense for me to apply the plugin and don't expect any work from the plugin.

I know that this statement is highly opinionated but I believe it handles the major use-case well.
