### ISSUE TITLE
Allow adding own WartTraversers to classpath

### ISSUE THREAD

**Issue by itsyaboiyeah** [augi/gradle-wartremover#31]
I would like to be able to define my own wart traversers elsewhere and arrange the appropriate classpath for this plugin to be forward into wartremover

http://www.wartremover.org/doc/install-setup.html

This can be done e.g. via '-P:wartremover:cp:path'

**Comment by augi** [comment]
It should be as easy as [defining excluded files](https://github.com/augi/gradle-wartremover/blob/master/src/main/groovy/cz/augi/gradle/wartremover/WartremoverPlugin.groovy#L26) so feel free to prepare a new PR. Thanks!
