### ISSUE TITLE
Add support for Scala 2.12.14

### ISSUE THREAD

**Issue by ColOfAbRiX** [augi/gradle-wartremover#54]
Gradle fails to find the wartremover artifacts for Scala 2.12.14. I'm using gradle-wartremover 0.14.0

```
> Could not resolve all files for configuration ':my-project'.
   > Could not find org.wartremover:wartremover_2.12.14:2.4.13.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/wartremover/wartremover_2.12.14/2.4.13/wartremover_2.12.14-2.4.13.pom
     Required by:
         project :my-project
```
Please update the getWartremoverArtifactSuffix to support Scala 2.12.14.

I see in https://repo.maven.apache.org/maven2/org/wartremover/wartremover_2.12.14/ that the correct getWartremoverArtifactSuffix should include either version 2.4.15 or 2.4.16

**Comment by augi** [comment]
Hello, thank you for reporting the issue. The fixed release is being released right now, `0.14.21.
