### ISSUE TITLE
test files rules 

### ISSUE THREAD

**Issue by NetanelRabinowitz** [augi/gradle-wartremover#6]
First of all Thanks for this awesome plugin!
I'm just getting started with wartremover 
my test file contains all kind of statements like this 

`result shouldBe expected`
wartremover is yielding this error: 

```
Error:(34, 14) [wartremover:NonUnitStatements] Statements must return Unit
      result shouldBe expected
```

is there a way to suppress this rule for tests?

**Comment by augi** [comment]
Hi, try something like this:
```gradle
wartremover {
    test {
        warningWarts.remove('NonUnitStatements')
    }
}
```

If it doesn't help, please reopen this issue.
