### ISSUE TITLE
Wartremover causes ScalaCompile task build cache misses

### ISSUE THREAD

**Issue by mvitaly** [augi/gradle-wartremover#73]
Wartremover plugin causes ScalaCompile task to have a cache key that is tied to the invoking user home directory. The result is build cache misses when working with (remote) cache that is shared between multiple users or computers. It's probably caused by the addition of the scala compiler plugin absolute path (`-Xplugin:`) to `scalaCompileOptions.additionalParameters`. I can see the full path when printing the additionalParameters modified by wartremover plugin.

Found this gradle PR https://github.com/gradle/gradle/pull/11615 that added a dedicated option to specify compiler plugins `scalaCompilerPlugins` that should provide an alternative to the use of absolute paths.

**Comment by augi** [comment]
Hello, thank you for reporting this issue! 👍

**Comment by augi** [comment]
Will be released shortly at `0.15.0`.
